const PACKET_TYPES = {
  REAL_MESSAGE: 'REAL_MESSAGE',
  COVER_TRAFFIC: 'COVER_TRAFFIC',
  FILE_PACKET: 'FILE_PACKET',
  FILE_META: 'FILE_META',
  NODE_HELLO: 'NODE_HELLO',
  ATTACKER_NODE_HELLO: 'ATTACKER_NODE_HELLO',
  ADMIN_ALERT: 'ADMIN_ALERT',
  INCIDENT: 'INCIDENT'
};

const INCIDENT_SEVERITY = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  CRITICAL: 'critical'
};

const WS_EVENTS = {
  SECURITY_SETTINGS_UPDATED: 'SECURITY_SETTINGS_UPDATED',
  COVER_TRAFFIC_CONFIG_UPDATED: 'COVER_TRAFFIC_CONFIG_UPDATED',
  ATTACKER_DEMO_SETTINGS_UPDATED: 'ATTACKER_DEMO_SETTINGS_UPDATED',
  ATTACKER_DEMO_PACKET: 'ATTACKER_DEMO_PACKET',
  NODE_AUTH_OK: 'NODE_AUTH_OK',
  NODE_AUTH_DENIED: 'NODE_AUTH_DENIED',
  JOIN_ROOM: 'JOIN_ROOM',
  ROOM_JOIN_OK: 'ROOM_JOIN_OK',
  ROOM_JOIN_DENIED: 'ROOM_JOIN_DENIED',
  SEND_DENIED: 'SEND_DENIED',
  CHAT_MESSAGE_RECEIVED: 'CHAT_MESSAGE_RECEIVED',
  INCIDENT_CREATED: 'INCIDENT_CREATED',
  ADMIN_SECURITY_ALERT: 'ADMIN_SECURITY_ALERT',
  SECURITY_ACTION_TAKEN: 'SECURITY_ACTION_TAKEN',
  FORCE_LOGOUT: 'FORCE_LOGOUT',
  USER_FORCE_LOGOUT_DONE: 'USER_FORCE_LOGOUT_DONE',
  ROOM_FROZEN: 'ROOM_FROZEN',
  ROOM_UNFROZEN: 'ROOM_UNFROZEN',
  SESSION_REVOKED: 'SESSION_REVOKED'
};

module.exports = {
  PACKET_TYPES,
  INCIDENT_SEVERITY,
  WS_EVENTS
};
