const PACKET_TYPES = {
  REAL_MESSAGE: 'REAL_MESSAGE',
  COVER_TRAFFIC: 'COVER_TRAFFIC',
  NODE_HELLO: 'NODE_HELLO',
  ATTACKER_NODE_HELLO: 'ATTACKER_NODE_HELLO',
  ADMIN_ALERT: 'ADMIN_ALERT',
  INCIDENT: 'INCIDENT'
};

const INCIDENT_SEVERITY = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  CRITICAL: 'critical'
};

const WS_EVENTS = {
  SECURITY_SETTINGS_UPDATED: 'SECURITY_SETTINGS_UPDATED',
  COVER_TRAFFIC_CONFIG_UPDATED: 'COVER_TRAFFIC_CONFIG_UPDATED',
  ATTACKER_DEMO_SETTINGS_UPDATED: 'ATTACKER_DEMO_SETTINGS_UPDATED',
  ATTACKER_DEMO_PACKET: 'ATTACKER_DEMO_PACKET',
  NODE_AUTH_OK: 'NODE_AUTH_OK',
  NODE_AUTH_DENIED: 'NODE_AUTH_DENIED',
  JOIN_ROOM: 'JOIN_ROOM',
  ROOM_JOIN_OK: 'ROOM_JOIN_OK',
  ROOM_JOIN_DENIED: 'ROOM_JOIN_DENIED',
  SEND_DENIED: 'SEND_DENIED',
  CHAT_MESSAGE_RECEIVED: 'CHAT_MESSAGE_RECEIVED'
};

module.exports = {
  PACKET_TYPES,
  INCIDENT_SEVERITY,
  WS_EVENTS
};
